refuel:
  maxtank: 10
  arrow:
    name: "energy cell"
    fills: 1
events:
  bumpyRide:
    injuryChance:
      1: 100
      2: 50
      3: 0
    damage: 8
    probability: 3
  infestation:
    number: 2
    poisonous: false
    probability: 2
  breakdown:
    probability: 2
    spareParts:
      glass: 
        name: "glass"
  none:
    probability: 3
  fuelLeak:
    probability: 1