refuel:
  maxtank: 10
events:
  bumpyRide:
    injuryChance:
    damage: 8
    probability: 3
  infestation:
    number: 2
    poisonous: false
    probability: 2
  breakdown:
    probability: 2
    spareParts:
    tools:
  none:
    probability: 3
  fuelLeak:
    probability: 1
limbo_name: space