refuel:
  maxtank: 10
  arrow:
    name: "energy cell"
    fills: 1
events:
  bumpyRide:
    damage: 8
    probability: 3
  infestation:
    number: 2
    poisonous: false
    probability: 2
  breakdown:
    probability: 2
    spareParts:
      bedrock: 
        name: "white Hull"
      glass: 
        name: "glass"
      enchanting_table: 
        name: "navigation screen"
      piston:
        name: "piston"
      redstone: 
        name: "copper wire"
    tools:
      ink_sack:
        name: "wrench"
      nether_star:
        name: "soldering iron"
      iron_sword: 
        name: "crowbar"
  none:
    probability: 5
  fuelLeak:
    probability: 1