name: HorizonShips
main: com.gmail.Rhisereld.HorizonShips.Main
version: 1.0
depend: [WorldEdit]
softdepend: [HorizonProfessions]
commands:
  ship:
    description: All Horizon Ships commands.
    aliases: hs

permissions:
  horizonships.*:
    description: Gives access to all Horizon Ships commands.
    children:
      horizonships.admin.ship.create: true
      horizonships.admin.ship.delete: true
      horizonships.admin.destination.add: true
      horizonships.admin.destination.remove: true
      horizonships.admin.setowner: true
      horizonships.admin.info: true
      horizonships.admin.canbuildinsideships: true
      horizonships.admin.pilot.add: true
      horizonships.admin.pilot.remove: true
      horizonships.admin.rename: true
      horizonships.list: true
      horizonships.pilot: true
      horizonships.diagnose: true
      horizonships.repair: true   
      horizonships.refuel: true
      horizonships.transfer: true
      horizonships.info: true
      horizonships.pilot.add: true
      horizonships.pilot.remove: true
      horizonships.rename: true
    
  horizonships.common:
    description: Gives access to Horizon Ships for normal players.
    children:
      horizonships.list: true
      horizonships.pilot: true
      horizonships.diagnose: true
      horizonships.repair: true
      horizonships.refuel: true
      horizonships.transfer: true
      horizonships.info: true
      horizonships.pilot.add: true
      horizonships.pilot.remove: true
      horizonships.rename: true
    
  horizonships.admin:
    description: Gives access to all Horizon Ships commands for admins and normal players.
    children:
      horizonships.admin.ship.create: true
      horizonships.admin.ship.delete: true
      horizonships.admin.destination.add: true
      horizonships.admin.destination.remove: true
      horizonships.admin.setowner: true
      horizonships.admin.info: true
      horizonships.admin.canbuildinsideships: true
      horizonships.admin.pilot.add: true
      horizonships.admin.pilot.remove: true
      horizonships.admin.rename: true
      horizonships.list: true
      horizonships.pilot: true
      horizonships.diagnose: true
      horizonships.repair: true
      horizonships.transfer: true
      horizonships.info: true
      horizonships.pilot.add: true
      horizonships.pilot.remove: true
      horizonships.rename: true
  